### ISSUE TITLE
Is this library done already?

### ISSUE THREAD

**Issue by basequatro** [line64/react-native-checkout-mercadopago#1]
And it works in any country that mercadopago works?

**Comment by scarmuega** [comment]
It hasn't been tested on production, but it does work currently on Android, we plan to push the iOS bridge code within the next two weeks.

Regarding countries, this library is only a bridge to the official MercadoPago components, so It should work in any country stated by the [official documentation](http://mercadopago.github.io/px-android/) 

If you have any issues while trying out the lib, we are welcome to help you out.

**Comment by basequatro** [comment]
Thanks for the info, i'll try out this week and let you know.
