### ISSUE TITLE
Add support for MercadoPago 3.2.0

### ISSUE THREAD

**Issue by JonatanSalas** [line64/react-native-checkout-mercadopago#11]
Hi! 

I want to tell you that I'm working on a newer version of this library on a fork, where I try to integrate the MercadoPago SDK v3.2.0 for Android/IOS. 

I have currently done with the Android setup. The newer version of this SDK provides the ability to start the checkout in two modes. One for Payment, and another one for PaymentData (Intended to be used when you work with MP Connect/MarketPlace). 

The current modifications to your codebase are the following ones: 
- Add the ability to customize checkout appearance through DecorationPreference class
- Add the ability to start the checkout in case of Payment, or PaymentData. 
- Some other minor modifications to the code related to the ActivityEventListener.

I have to work still on the IOS part. 

Are you currently interested in the possibility of merging my changes? If so, let me know, and I will open a PR, where you can track my development progress.

**Comment by scarmuega** [comment]
@JonatanSalas thank you very much, your PR will be more than welcome.

**Comment by JonatanSalas** [comment]
@scarmuega Great! I will open a PR so you can keep track.

**Comment by JonatanSalas** [comment]
@scarmuega PR is able to merge!
