### ISSUE TITLE
Error on compilation Android

### ISSUE THREAD

**Issue by improve-ar** [line64/react-native-checkout-mercadopago#3]
Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

**Comment by improve-ar** [comment]
Now i have this error Process 'command '/home/juan/.android/build-tools/23.0.1/aapt'' finished with non-zero exit value 1

**Comment by a-sierra** [comment]
Hi, @juanmanuelarze, try updating versions of the `android/app/build.gradle` files from both, your project and the module, to the following: 

```
android {
  compileSdkVersion 24
  buildToolsVersion "24.0.1"
}
```

Please, let me know if you are still getting the error.
