### ISSUE TITLE
Type error: undefined is not an object (CheckoutMercadoPagoModule.startCheckout)

### ISSUE THREAD

**Issue by jonatasdlp** [line64/react-native-checkout-mercadopago#5]
I trying to run example app but mercadopago sdk components is not working.

Are there any extra step?

![screen shot 2017-03-29 at 21 49 34](https://cloud.githubusercontent.com/assets/1140715/24482783/3e472ea2-14ca-11e7-97b6-ee10a2e9f993.png)

**Comment by JonatanSalas** [comment]
Currently having the same issue. Hey guys, would you mind to check the example app?

**Comment by JonatanSalas** [comment]
@scarmuega I have made checkout work on Android. This issue only happens on IOS. When you distribute the package, do you link the MercadoPago SDK to the library, or do we have to link it?

**Comment by scarmuega** [comment]
@JonatanSalas the actual MercadoPago SDK should be installed independently following the instructions from the official site. Once you have that in place, you can install and link this bridge package.

TBH, I have to test the whole procedure in a blank project to confirm that it still works with the latest version of the SDK. I'll try to do it this week, and I'll come back to this issue. If you have any luck, please let me know.

**Comment by JonatanSalas** [comment]
I have done it with Android! If you want I can give you a blank project where I have been testing. To do so, I have modified the gradle dependencies from the package by forking the repository.

**Comment by JonatanSalas** [comment]
Thanks for support!

**Comment by JonatanSalas** [comment]
@scarmuega I have found something related to this issue. When reviewing the module in node_modules folder there's only code related to Android. Is this normal? See attached images.

<img width="360" alt="node_modules" src="https://cloud.githubusercontent.com/assets/7697196/26653976/5fd20f6e-462b-11e7-86ae-460c412decb6.png">

This is the package.json, the library version is v0.2.0:

<img width="1440" alt="ide" src="https://cloud.githubusercontent.com/assets/7697196/26654008/836b09bc-462b-11e7-9cff-1a4910fc28d0.png">

**Comment by JonatanSalas** [comment]
@scarmuega would you mind to verify the content of release v0.2.0. If the error is related to this, it's currently easy to fix by releasing a newer library version. 

As a hot fix, I will fork the library and release a fix version, also, I will try to integrate new mercadopago SDK and test it. When this issue it's fixed, I will remove my version from npm. Is it okey for you?

**Comment by scarmuega** [comment]
@JonatanSalas I'll do a fresh publish to NPM to see if it fixes the issue. Otherwise, a PR would be more than welcome!

**Comment by scarmuega** [comment]
@JonatanSalas published! please try out version 0.3.0.

**Comment by JonatanSalas** [comment]
@scarmuega I will try it, and let you know! Thanks for your effort 😄

**Comment by JonatanSalas** [comment]
@scarmuega I have tested but still the same issue, I will try to probe on my own, and if I solve it I will submit a PR.

**Comment by JonatanSalas** [comment]
@scarmuega It seems to be a configuration issue, I have fixed it in the example app you provide.

**Comment by improve-ar** [comment]
import NativeModules from react-native

const Mercadopago = NativeModules.CheckoutMercadoPagoModule;
Mercadopago.startCheckout(xxx,xxx)

**Comment by scarmuega** [comment]
@JonatanSalas I published a new version to npm after merging your PR. Please ping me if it works as expected.

**Comment by JonatanSalas** [comment]
@scarmuega We've made it work with the latest release you've made! So, thank you! You can close now the issue. Also, the PR I have made, was only with the purpose of upgrading the example mobile app.

**Comment by githubmss** [comment]
i am getting same issue again
